use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};

use crate::credentials::{CredentialSource, CredentialStore};

pub const DEFAULT_INSTANCE_URL: &str = "https://app.rustgrid.com";
pub const DEFAULT_API_URL: &str = "https://app.rustgrid.com/api/v1";

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// RustGrid control-plane instance. The `/api/v1` suffix is optional.
    #[serde(default)]
    pub instance_url: Option<String>,
    /// Stable identity for this installation. Generated by `login` and never secret.
    #[serde(default)]
    pub installation_id: Option<String>,
    /// Device-authenticated worker metadata. The access token is never stored here.
    #[serde(default)]
    pub worker_id: Option<String>,
    #[serde(default)]
    pub tenant_id: Option<String>,
    #[serde(default)]
    pub worker_name: Option<String>,
    /// Non-secret description of where the interactive credential is stored.
    #[serde(default)]
    pub credential_store: Option<String>,
    /// Non-secret Unix expiry timestamp for an interactive device credential.
    #[serde(default)]
    pub credential_expires_at_unix: Option<u64>,
    /// Deprecated compatibility hint. Tenant workers accept runs from every
    /// project authorized by the control plane.
    #[serde(default)]
    pub project_id: Option<String>,
    /// Deprecated compatibility hint. Tenant workers accept runs from every
    /// project authorized by the control plane.
    #[serde(default)]
    pub project_key: Option<String>,
    #[serde(default)]
    pub repo: Option<RepoConfig>,
    #[serde(default = "default_base_branch")]
    pub default_base_branch: String,
    #[serde(default)]
    pub quality_gate_command: Option<String>,
    #[serde(default)]
    pub codex_command: Option<String>,
    #[serde(default = "default_heartbeat_interval_seconds")]
    pub heartbeat_interval_seconds: u64,
    #[serde(default = "default_max_concurrency")]
    pub max_concurrency: usize,
    #[serde(default)]
    pub executor: ExecutorConfig,
    #[serde(default = "default_lease_seconds")]
    pub lease_seconds: u64,
    #[serde(default)]
    pub workspace_root: Option<PathBuf>,
    #[serde(default = "default_command_timeout_seconds")]
    pub command_timeout_seconds: u64,
    #[serde(default = "default_run_timeout_seconds")]
    pub run_timeout_seconds: u64,
    #[serde(default = "default_failed_workspace_retention_hours")]
    pub failed_workspace_retention_hours: u64,
    #[serde(default = "default_max_command_output_bytes")]
    pub max_command_output_bytes: u64,
    #[serde(default = "default_max_workspace_bytes")]
    pub max_workspace_bytes: u64,
    #[serde(default = "default_max_child_memory_bytes")]
    pub max_child_memory_bytes: u64,
    #[serde(default = "default_max_child_file_bytes")]
    pub max_child_file_bytes: u64,
    #[serde(default = "default_max_child_open_files")]
    pub max_child_open_files: u64,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum ExecutorConfig {
    #[default]
    Local,
    DockerSandbox {
        #[serde(default = "default_sbx_command")]
        command: String,
        #[serde(default = "default_sandbox_template")]
        template: String,
        #[serde(default = "default_codex_version")]
        codex_version: String,
        #[serde(default = "default_sandbox_cpus")]
        cpus: u16,
        #[serde(default = "default_sandbox_memory")]
        memory: String,
        #[serde(default = "default_sandbox_capacity_cpus")]
        capacity_cpus: u16,
        #[serde(default = "default_sandbox_capacity_memory")]
        capacity_memory: String,
    },
}

impl ExecutorConfig {
    fn production_default() -> Self {
        Self::DockerSandbox {
            command: default_sbx_command(),
            template: default_sandbox_template(),
            codex_version: default_codex_version(),
            cpus: default_sandbox_cpus(),
            memory: default_sandbox_memory(),
            capacity_cpus: default_sandbox_capacity_cpus(),
            capacity_memory: default_sandbox_capacity_memory(),
        }
    }

    pub fn is_isolated(&self) -> bool {
        matches!(self, Self::DockerSandbox { .. })
    }

    pub fn kind(&self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::DockerSandbox { .. } => "docker_sandbox",
        }
    }

    pub(crate) fn validate_production(&self, max_concurrency: usize) -> Result<()> {
        let Self::DockerSandbox {
            template,
            codex_version,
            cpus,
            memory,
            capacity_cpus,
            capacity_memory,
            ..
        } = self
        else {
            bail!("executor.kind=docker_sandbox is required for production");
        };
        let digest = template.split_once("@sha256:").map(|(_, value)| value);
        if !digest
            .is_some_and(|value| value.len() == 64 && value.chars().all(|c| c.is_ascii_hexdigit()))
        {
            bail!("production sandbox template must be pinned by a 64-character sha256 digest");
        }
        validate_codex_version(codex_version)?;
        let required_cpus = usize::from(*cpus).saturating_mul(max_concurrency);
        if required_cpus > usize::from(*capacity_cpus) {
            bail!("sandbox CPU allocation exceeds configured host capacity");
        }
        let required_memory = parse_binary_size(memory)?.saturating_mul(max_concurrency as u64);
        if required_memory > parse_binary_size(capacity_memory)? {
            bail!("sandbox memory allocation exceeds configured host capacity");
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RepoConfig {
    pub owner: String,
    pub name: String,
}

#[derive(Clone, Debug)]
pub struct AppContext {
    pub config: Config,
    pub config_path: PathBuf,
    pub instance_url: String,
    pub api_url: String,
    pub api_key: Option<String>,
    pub worker_id: Option<String>,
    pub tenant_id: Option<String>,
    pub worker_name: Option<String>,
    pub installation_id: String,
    pub credential_source: CredentialSource,
    pub credential_expires_at_unix: Option<u64>,
    pub credential_store: CredentialStore,
    /// Legacy plaintext sidecar path, retained only for one-time migration.
    pub credentials_path: PathBuf,
    pub workspace_root: PathBuf,
}

fn default_base_branch() -> String {
    "main".into()
}

fn default_heartbeat_interval_seconds() -> u64 {
    15
}

fn default_max_concurrency() -> usize {
    1
}

fn default_sbx_command() -> String {
    "sbx".into()
}
fn default_sandbox_template() -> String {
    "docker.io/docker/sandbox-templates@sha256:943c52aa48a4f4473a9c91e43aced8def51667935ad9866ffc29a821d5982f97".into()
}
fn default_codex_version() -> String {
    "0.144.4".into()
}
fn default_sandbox_cpus() -> u16 {
    4
}
fn default_sandbox_memory() -> String {
    "8g".into()
}
fn default_sandbox_capacity_cpus() -> u16 {
    4
}
fn default_sandbox_capacity_memory() -> String {
    "8g".into()
}

fn parse_binary_size(value: &str) -> Result<u64> {
    let normalized = value.trim().to_ascii_lowercase();
    let split = normalized
        .find(|c: char| !c.is_ascii_digit())
        .unwrap_or(normalized.len());
    let number: u64 = normalized[..split]
        .parse()
        .context("memory size must start with a number")?;
    if number == 0 {
        bail!("memory size must be greater than zero");
    }
    let multiplier = match &normalized[split..] {
        "" | "b" => 1,
        "k" | "kb" | "kib" => 1024,
        "m" | "mb" | "mib" => 1024 * 1024,
        "g" | "gb" | "gib" => 1024 * 1024 * 1024,
        _ => bail!("memory size must use b, k, m, or g binary units"),
    };
    number
        .checked_mul(multiplier)
        .context("memory size overflow")
}

fn validate_codex_version(value: &str) -> Result<()> {
    let components = value.split('.').collect::<Vec<_>>();
    if components.len() != 3
        || components
            .iter()
            .any(|component| component.is_empty() || !component.chars().all(|c| c.is_ascii_digit()))
    {
        bail!("docker sandbox codex_version must be an exact numeric version such as 0.144.4");
    }
    Ok(())
}

fn default_lease_seconds() -> u64 {
    900
}

fn default_command_timeout_seconds() -> u64 {
    1800
}

fn default_run_timeout_seconds() -> u64 {
    7200
}

fn default_failed_workspace_retention_hours() -> u64 {
    72
}

fn default_max_command_output_bytes() -> u64 {
    8 * 1024 * 1024
}

fn default_max_workspace_bytes() -> u64 {
    5 * 1024 * 1024 * 1024
}

fn default_max_child_memory_bytes() -> u64 {
    8 * 1024 * 1024 * 1024
}

fn default_max_child_file_bytes() -> u64 {
    1024 * 1024 * 1024
}

fn default_max_child_open_files() -> u64 {
    1024
}

impl AppContext {
    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)
            .with_context(|| format!("could not read config file {}", path.display()))?;
        let config = parse_config(path, &bytes)?;
        Self::from_config(path, config, true)
    }

    pub fn load_for_login(path: &Path, instance_override: Option<&str>) -> Result<Self> {
        let (mut config, created) = match fs::read(path) {
            Ok(bytes) => (parse_config(path, &bytes)?, false),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                (first_login_config()?, true)
            }
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("could not read config file {}", path.display()));
            }
        };
        let mut changed = created;
        if config.installation_id.is_none() {
            config.installation_id = Some(uuid::Uuid::new_v4().to_string());
            changed = true;
        }
        if let Some(instance) = instance_override {
            config.instance_url = Some(normalize_instance_url(instance)?);
            changed = true;
        }
        config.validate()?;
        if changed {
            save_config(path, &config)?;
        }
        Self::from_config(path, config, true)
    }

    fn from_config(path: &Path, mut config: Config, persist_identity: bool) -> Result<Self> {
        config.validate()?;
        let mut identity_changed = false;
        let installation_id = match config.installation_id.clone() {
            Some(value) => value,
            None => {
                let value = uuid::Uuid::new_v4().to_string();
                config.installation_id = Some(value.clone());
                identity_changed = true;
                value
            }
        };
        uuid::Uuid::parse_str(&installation_id).context("installation_id must be a valid UUID")?;

        let saved_instance = normalize_instance_url(
            config
                .instance_url
                .as_deref()
                .unwrap_or(DEFAULT_INSTANCE_URL),
        )?;
        if config.instance_url.as_deref() != Some(saved_instance.as_str()) {
            config.instance_url = Some(saved_instance.clone());
            identity_changed = true;
        }
        let configured_instance = match nonempty_env("RUSTGRID_INSTANCE_URL") {
            Some(value) => normalize_instance_url(&value)?,
            None => saved_instance,
        };
        let (instance_url, api_url) = match nonempty_env("RUSTGRID_API_URL") {
            Some(url) => {
                let api_url = normalize_legacy_api_url(&url)?;
                (instance_from_api_url(&api_url), api_url)
            }
            None => (
                configured_instance.clone(),
                api_url_for_instance(&configured_instance),
            ),
        };

        let credential_store = CredentialStore::new(&api_url, &installation_id)?;
        let credentials_path = credentials_path(path);
        let env_key = nonempty_env("RUSTGRID_WORKER_API_KEY");
        let (mut api_key, mut credential_source) = if let Some(key) = env_key.as_ref() {
            (Some(key.clone()), CredentialSource::Environment)
        } else {
            credential_store.load()?
        };
        let mut worker_id = nonempty_env("RUSTGRID_WORKER_ID").or_else(|| config.worker_id.clone());

        if api_key.is_none()
            && let Some(legacy) = LegacyStoredCredentials::load(&credentials_path)?
        {
            let source = credential_store.save(&legacy.api_key)?;
            api_key = Some(legacy.api_key);
            credential_source = source;
            if worker_id.is_none() {
                worker_id = Some(legacy.worker_id.clone());
                config.worker_id = Some(legacy.worker_id);
            }
            fs::remove_file(&credentials_path).with_context(|| {
                format!(
                    "could not remove migrated credentials file {}",
                    credentials_path.display()
                )
            })?;
            eprintln!(
                "[warning] Migrated the legacy plaintext credential sidecar into {}",
                credential_source.as_str()
            );
            identity_changed = true;
        }
        if let Some(worker_id) = worker_id.as_deref() {
            uuid::Uuid::parse_str(worker_id).context("worker ID must be a valid UUID")?;
        }
        if let Some(tenant_id) = config.tenant_id.as_deref() {
            uuid::Uuid::parse_str(tenant_id).context("tenant ID must be a valid UUID")?;
        }
        if env_key.is_none() {
            let source = if credential_source == CredentialSource::Missing {
                None
            } else {
                Some(credential_source.as_str().to_owned())
            };
            if config.credential_store != source {
                config.credential_store = source;
                identity_changed = true;
            }
        }
        if identity_changed && persist_identity {
            save_config(path, &config)?;
        }

        let workspace_root = config.workspace_root.clone().unwrap_or_else(|| {
            std::env::temp_dir()
                .join("rustgrid-agent")
                .join("workspaces")
        });
        let credential_expires_at_unix = if env_key.is_some() {
            None
        } else {
            config.credential_expires_at_unix
        };
        Ok(Self {
            tenant_id: config.tenant_id.clone(),
            worker_name: config.worker_name.clone(),
            config,
            config_path: path.to_path_buf(),
            instance_url,
            api_url,
            api_key,
            worker_id,
            installation_id,
            credential_source,
            credential_expires_at_unix,
            credential_store,
            credentials_path,
            workspace_root,
        })
    }

    pub fn save_login(
        &mut self,
        access_token: &str,
        worker_id: &str,
        tenant_id: &str,
        worker_name: &str,
        expires_in: u64,
    ) -> Result<()> {
        uuid::Uuid::parse_str(worker_id).context("login returned an invalid worker ID")?;
        uuid::Uuid::parse_str(tenant_id).context("login returned an invalid tenant ID")?;
        let source = self.credential_store.save(access_token)?;
        self.config.instance_url = Some(self.instance_url.clone());
        self.config.installation_id = Some(self.installation_id.clone());
        self.config.worker_id = Some(worker_id.to_owned());
        self.config.tenant_id = Some(tenant_id.to_owned());
        self.config.worker_name = Some(worker_name.to_owned());
        self.config.credential_store = Some(source.as_str().to_owned());
        let credential_expires_at_unix = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .context("system clock is before the Unix epoch")?
            .as_secs()
            .saturating_add(expires_in);
        self.config.credential_expires_at_unix = Some(credential_expires_at_unix);
        save_config(&self.config_path, &self.config)?;
        self.api_key = Some(access_token.to_owned());
        self.worker_id = Some(worker_id.to_owned());
        self.tenant_id = Some(tenant_id.to_owned());
        self.worker_name = Some(worker_name.to_owned());
        self.credential_source = source;
        self.credential_expires_at_unix = Some(credential_expires_at_unix);
        Ok(())
    }

    pub fn clear_login(&mut self) -> Result<()> {
        self.credential_store.delete()?;
        self.config.worker_id = None;
        self.config.tenant_id = None;
        self.config.worker_name = None;
        self.config.credential_store = None;
        self.config.credential_expires_at_unix = None;
        save_config(&self.config_path, &self.config)?;
        self.api_key = None;
        self.worker_id = None;
        self.tenant_id = None;
        self.worker_name = None;
        self.credential_source = CredentialSource::Missing;
        self.credential_expires_at_unix = None;
        Ok(())
    }

    pub fn require_api_key(&self) -> Result<&str> {
        self.api_key
            .as_deref()
            .context("worker authentication is required; run `rustgrid-agent login`")
    }

    pub fn require_worker_id(&self) -> Result<&str> {
        self.worker_id
            .as_deref()
            .context("worker authentication is required; run `rustgrid-agent login`")
    }
}

fn first_login_config() -> Result<Config> {
    let mut config = serde_json::from_str::<Config>("{}")?;
    config.executor = ExecutorConfig::production_default();
    Ok(config)
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct LegacyStoredCredentials {
    pub worker_id: String,
    pub api_key: String,
}

impl LegacyStoredCredentials {
    fn load(path: &Path) -> Result<Option<Self>> {
        let bytes = match fs::read(path) {
            Ok(bytes) => bytes,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(error) => {
                return Err(error).with_context(|| format!("could not read {}", path.display()));
            }
        };
        let value: Self = serde_json::from_slice(&bytes)
            .with_context(|| format!("invalid credentials file {}", path.display()))?;
        uuid::Uuid::parse_str(&value.worker_id)
            .with_context(|| format!("invalid worker ID in {}", path.display()))?;
        if value.api_key.trim().is_empty() {
            bail!("empty API key in {}", path.display());
        }
        Ok(Some(value))
    }
}

fn credentials_path(config_path: &Path) -> PathBuf {
    let name = config_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("agent.json");
    config_path.with_file_name(format!("{name}.credentials"))
}

fn parse_config(path: &Path, bytes: &[u8]) -> Result<Config> {
    let config: Config = serde_json::from_slice(bytes)
        .with_context(|| format!("invalid JSON configuration in {}", path.display()))?;
    config.validate()?;
    Ok(config)
}

fn save_config(path: &Path, config: &Config) -> Result<()> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;
    if let Ok(metadata) = fs::symlink_metadata(path)
        && (metadata.file_type().is_symlink() || !metadata.is_file())
    {
        bail!(
            "refusing to replace non-regular config path {}",
            path.display()
        );
    }
    let temporary = parent.join(format!(".rustgrid-agent-{}.tmp", uuid::Uuid::new_v4()));
    write_private_file(&temporary, &serde_json::to_vec_pretty(config)?)?;
    fs::rename(&temporary, path)
        .with_context(|| format!("could not save config to {}", path.display()))?;
    Ok(())
}

pub fn normalize_instance_url(value: &str) -> Result<String> {
    let mut url = reqwest::Url::parse(value.trim()).context("invalid RustGrid instance URL")?;
    validate_control_plane_url(&url)?;
    let path = url.path().trim_end_matches('/');
    match path {
        "" => url.set_path("/"),
        "/api/v1" => url.set_path("/"),
        _ => bail!("RustGrid instance URL path must be empty or /api/v1"),
    }
    Ok(url.to_string().trim_end_matches('/').to_owned())
}

/// Compatibility normalizer for the pre-device-auth API override. Unlike an
/// instance URL, this may point at a custom reverse-proxy prefix.
pub fn normalize_legacy_api_url(value: &str) -> Result<String> {
    let url = reqwest::Url::parse(value.trim()).context("invalid RustGrid API URL")?;
    validate_control_plane_url(&url)?;
    if url.path() == "/" || url.path().is_empty() {
        return Ok(api_url_for_instance(url.as_str().trim_end_matches('/')));
    }
    Ok(url.to_string().trim_end_matches('/').to_owned())
}

fn validate_control_plane_url(url: &reqwest::Url) -> Result<()> {
    if !url.username().is_empty()
        || url.password().is_some()
        || url.query().is_some()
        || url.fragment().is_some()
    {
        bail!("RustGrid URL must not include credentials, query parameters, or fragments");
    }
    let local = matches!(url.host_str(), Some("localhost" | "127.0.0.1" | "::1"));
    if url.scheme() != "https" && !(url.scheme() == "http" && local) {
        bail!("RustGrid URL must use HTTPS (HTTP is allowed only for localhost)");
    }
    Ok(())
}

fn api_url_for_instance(instance_url: &str) -> String {
    format!("{}/api/v1", instance_url.trim_end_matches('/'))
}

fn instance_from_api_url(api_url: &str) -> String {
    api_url
        .strip_suffix("/api/v1")
        .unwrap_or(api_url)
        .trim_end_matches('/')
        .to_owned()
}

#[cfg(unix)]
fn write_private_file(path: &Path, contents: &[u8]) -> Result<()> {
    use std::{io::Write, os::unix::fs::OpenOptionsExt};
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)?;
    file.write_all(contents)?;
    file.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn write_private_file(path: &Path, contents: &[u8]) -> Result<()> {
    fs::write(path, contents).map_err(Into::into)
}

impl Config {
    fn validate(&self) -> Result<()> {
        if let Some(instance_url) = self.instance_url.as_deref() {
            normalize_instance_url(instance_url)?;
        }
        for (name, value) in [
            ("installation_id", self.installation_id.as_deref()),
            ("worker_id", self.worker_id.as_deref()),
            ("tenant_id", self.tenant_id.as_deref()),
        ] {
            if let Some(value) = value {
                uuid::Uuid::parse_str(value)
                    .with_context(|| format!("{name} must be a valid UUID"))?;
            }
        }
        if self
            .worker_name
            .as_ref()
            .is_some_and(|value| value.trim().is_empty() || value.len() > 255)
        {
            bail!("worker_name must be between 1 and 255 characters");
        }
        for (name, value) in [("default_base_branch", self.default_base_branch.as_str())] {
            if value.trim().is_empty() {
                bail!("config value {name} cannot be empty");
            }
        }
        if !(5..=300).contains(&self.heartbeat_interval_seconds) {
            bail!("heartbeat_interval_seconds must be between 5 and 300");
        }
        if !(1..=100).contains(&self.max_concurrency) {
            bail!("max_concurrency must be between 1 and 100");
        }
        match &self.executor {
            ExecutorConfig::Local if self.max_concurrency != 1 => {
                bail!("local executor requires max_concurrency=1")
            }
            ExecutorConfig::DockerSandbox {
                command,
                template,
                codex_version,
                cpus,
                memory,
                capacity_cpus,
                capacity_memory,
            } => {
                if command.trim().is_empty()
                    || template.trim().is_empty()
                    || codex_version.trim().is_empty()
                    || memory.trim().is_empty()
                    || capacity_memory.trim().is_empty()
                {
                    bail!("docker sandbox command, template, and memory cannot be empty");
                }
                validate_codex_version(codex_version)?;
                if !(1..=64).contains(cpus) {
                    bail!("docker sandbox cpus must be between 1 and 64");
                }
                if !(1..=256).contains(capacity_cpus) {
                    bail!("docker sandbox capacity_cpus must be between 1 and 256");
                }
                parse_binary_size(memory)?;
                parse_binary_size(capacity_memory)?;
            }
            ExecutorConfig::Local => {}
        }
        if !(30..=86_400).contains(&self.lease_seconds) {
            bail!("lease_seconds must be between 30 and 86400");
        }
        if self.heartbeat_interval_seconds.saturating_mul(3) >= self.lease_seconds {
            bail!("lease_seconds must exceed three heartbeat intervals");
        }
        if self.failed_workspace_retention_hours > 24 * 30 {
            bail!("failed_workspace_retention_hours cannot exceed 720");
        }
        if self.max_command_output_bytes < 64 * 1024 {
            bail!("max_command_output_bytes must be at least 65536");
        }
        if self.max_workspace_bytes < 64 * 1024 * 1024 {
            bail!("max_workspace_bytes must be at least 67108864");
        }
        if self.max_child_memory_bytes < 256 * 1024 * 1024 {
            bail!("max_child_memory_bytes must be at least 268435456");
        }
        if self.max_child_file_bytes < 1024 * 1024 {
            bail!("max_child_file_bytes must be at least 1048576");
        }
        if !(64..=65_536).contains(&self.max_child_open_files) {
            bail!("max_child_open_files must be between 64 and 65536");
        }
        Ok(())
    }
}

fn nonempty_env(name: &str) -> Option<String> {
    env::var(name).ok().filter(|value| !value.trim().is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_tenant_scoped_configuration_without_a_project() {
        let config = Config {
            instance_url: None,
            installation_id: None,
            worker_id: None,
            tenant_id: None,
            worker_name: None,
            credential_store: None,
            credential_expires_at_unix: None,
            project_id: None,
            project_key: None,
            repo: Some(RepoConfig {
                owner: "o".into(),
                name: "r".into(),
            }),
            default_base_branch: "main".into(),
            quality_gate_command: None,
            codex_command: None,
            heartbeat_interval_seconds: 15,
            max_concurrency: 1,
            executor: ExecutorConfig::Local,
            lease_seconds: 900,
            workspace_root: None,
            command_timeout_seconds: 1800,
            run_timeout_seconds: 7200,
            failed_workspace_retention_hours: 72,
            max_command_output_bytes: 8 * 1024 * 1024,
            max_workspace_bytes: 5 * 1024 * 1024 * 1024,
            max_child_memory_bytes: 8 * 1024 * 1024 * 1024,
            max_child_file_bytes: 1024 * 1024 * 1024,
            max_child_open_files: 1024,
        };
        config.validate().unwrap();
    }

    #[test]
    fn legacy_project_selectors_do_not_lock_the_worker() {
        let config: Config = serde_json::from_str(
            r#"{"project_id":"legacy-id","project_key":"LEGACY","max_concurrency":1}"#,
        )
        .unwrap();

        config.validate().unwrap();
    }

    #[test]
    fn rejects_concurrent_local_execution() {
        let mut config: Config = serde_json::from_str(
            r#"{"project_key":"RG","max_concurrency":2,"executor":{"kind":"local"}}"#,
        )
        .unwrap();
        assert!(
            config
                .validate()
                .unwrap_err()
                .to_string()
                .contains("local executor")
        );
        config.executor = ExecutorConfig::DockerSandbox {
            command: "sbx".into(),
            template: "test".into(),
            codex_version: "0.144.4".into(),
            cpus: 1,
            memory: "1g".into(),
            capacity_cpus: 2,
            capacity_memory: "2g".into(),
        };
        config.validate().unwrap();
    }

    #[test]
    fn production_requires_digest_and_capacity() {
        let mutable = ExecutorConfig::DockerSandbox {
            command: "sbx".into(),
            template: "example:latest".into(),
            codex_version: "0.144.4".into(),
            cpus: 4,
            memory: "8g".into(),
            capacity_cpus: 8,
            capacity_memory: "16g".into(),
        };
        assert!(mutable.validate_production(2).is_err());
        let pinned = ExecutorConfig::DockerSandbox {
            command: "sbx".into(),
            template: format!("example@sha256:{}", "a".repeat(64)),
            codex_version: "0.144.4".into(),
            cpus: 4,
            memory: "8g".into(),
            capacity_cpus: 8,
            capacity_memory: "16g".into(),
        };
        pinned.validate_production(2).unwrap();
        assert!(pinned.validate_production(3).is_err());
    }

    #[test]
    fn docker_sandbox_defaults_to_the_pinned_codex_release() {
        let executor: ExecutorConfig = serde_json::from_str(
            r#"{"kind":"docker_sandbox","template":"example","cpus":1,"memory":"1g","capacity_cpus":1,"capacity_memory":"1g"}"#,
        )
        .unwrap();
        let ExecutorConfig::DockerSandbox { codex_version, .. } = executor else {
            panic!("expected Docker Sandbox executor");
        };
        assert_eq!(codex_version, "0.144.4");
        assert!(validate_codex_version("0.144").is_err());
        assert!(validate_codex_version("latest").is_err());
    }

    #[test]
    fn first_login_uses_a_production_ready_single_worker_executor() {
        let config = first_login_config().unwrap();
        assert_eq!(config.max_concurrency, 1);
        let executor = config.executor;

        executor.validate_production(1).unwrap();
        let ExecutorConfig::DockerSandbox {
            command,
            cpus,
            memory,
            capacity_cpus,
            capacity_memory,
            ..
        } = executor
        else {
            panic!("first login must configure Docker Sandbox");
        };
        assert_eq!(command, "sbx");
        assert_eq!(cpus, capacity_cpus);
        assert_eq!(memory, capacity_memory);
    }

    #[test]
    fn legacy_login_credentials_can_be_read_for_migration() {
        let directory = tempfile::tempdir().unwrap();
        let credentials_path = directory.path().join("agent.json.credentials");
        let credentials = LegacyStoredCredentials {
            worker_id: "00000000-0000-4000-8000-000000000001".into(),
            api_key: "rgk_test".into(),
        };
        write_private_file(
            &credentials_path,
            &serde_json::to_vec(&credentials).unwrap(),
        )
        .unwrap();

        let loaded = LegacyStoredCredentials::load(&credentials_path)
            .unwrap()
            .unwrap();
        assert_eq!(loaded.worker_id, credentials.worker_id);
        assert_eq!(loaded.api_key, credentials.api_key);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(credentials_path).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
    }

    #[test]
    fn normalizes_instance_urls_and_rejects_remote_http() {
        assert_eq!(
            normalize_instance_url("https://example.com/api/v1").unwrap(),
            "https://example.com"
        );
        assert_eq!(
            api_url_for_instance(&normalize_instance_url("http://localhost:8080").unwrap()),
            "http://localhost:8080/api/v1"
        );
        assert_eq!(
            normalize_legacy_api_url("https://example.com/custom/proxy").unwrap(),
            "https://example.com/custom/proxy"
        );
        assert!(normalize_instance_url("http://example.com").is_err());
        assert!(normalize_instance_url("https://example.com/custom").is_err());
    }
}
