pub mod api;
pub mod attachments;
pub mod auth;
pub mod command;
pub mod config;
pub mod coordinator;
pub mod credentials;
pub mod error;
mod execution;
pub mod execution_graph;
// Protocol v1 is intentionally compiled but not routed to production while its
// conformance suite and backend contract are built phase by phase.
#[allow(dead_code)]
mod execution_protocol;
mod executor;
mod finalization;
pub mod git;
pub mod github;
pub mod health;
pub mod hosted;
pub mod hosted_orchestrator;
pub mod hosted_simulation;
pub mod journal;
pub mod lifecycle;
pub mod manifest;
pub mod mission;
pub mod optimization;
pub mod outcome;
pub mod prompt;
mod publishing;
mod reporting;
pub mod run_error;
pub mod runner;
pub mod setup;
pub mod shutdown;
pub mod supervisor;
pub mod telemetry;
pub mod token;
pub mod token_consumption;
pub mod workspace;
